# Disable blank line at start of prompt
add_newline = false

# [line_break]
# disabled = true

[character]
vicmd_symbol = '[V](bold blue)'

[username]
format = '\[[$user](bold green)'
disabled = false
show_always = true

[hostname]
format = '[@$hostname](bold green)\] '
ssh_only = false
disabled = false
