# Disable blank line at start of prompt
# add_newline = true

# [line_break]
# disabled = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#00897b"

[character]
error_symbol = "[❯](red)"
success_symbol = "[❯](green)"
vicmd_symbol = "[❮](blue)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"
truncation_length = 20

[git_status]
conflicted = "​"
deleted = "​"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
modified = "​"
renamed = "​"
staged = "​"
stashed = "≡"
style = "cyan"
untracked = "​"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
symbol = "py "

[package]
disabled = true
